language: node_js
node_js:
  - "10"
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - npm i
script:
  - npm run test
  - codecov
after_success:
  - export CODECOV_TOKEN="409d5197-8b4e-427c-9c9b-b07905e12660"
  - bash <(curl -s https://codecov.io/bash)
