language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - npm i
script:
  - npm run test
  - codecov
after_success:
  - export CODECOV_TOKEN="a59e9df8-1f1c-47da-8c51-2131b0284727"
  - bash <(curl -s https://codecov.io/bash) -s coverage/
