language: node_js
node_js:
  - "10"
sudo: required
addons:
	- chrome: stable
before_install: 
  - npm i -g codecov
install:
  - npm i
script:
  - npm run test
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage/
