language: node_js
node_js:
  - "10"
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - npm i
script:
  - npm run test
  - codecov
after_success:
  - export CODECOV_TOKEN=e88e9099-fc9d-4b60-8a66-4e3fdccde64c
  - bash <(curl -s https://codecov.io/bash)
